executable	= /afs/cern.ch/user/c/cvu/HistFitterTutorial/batch/channel1_type1_testtarget/HF_Batch_channel1_type1_testtarget.sh
arguments	= $(ClusterId) $(ProcId)
output		= /afs/cern.ch/user/c/cvu/HistFitterTutorial/batch/channel1_type1_testtarget/HF_Batch_channel1_type1_testtarget.out
error		= /afs/cern.ch/user/c/cvu/HistFitterTutorial/batch/channel1_type1_testtarget/HF_Batch_channel1_type1_testtarget.err
log		= /afs/cern.ch/user/c/cvu/HistFitterTutorial/batch/channel1_type1_testtarget/HF_Batch_channel1_type1_testtarget.log
+JobFlavour	= "tomorrow"

queue
